[project]
name = "sign-transcription"
description = "Models involved in transcribing sign language"
version = "0.0.1"
authors = [
    { name = "Amit Moryossef", email = "amitmoryossef@gmail.com" }
]
readme = "README.md"

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint"
]

[tool.setuptools]
packages = [
    "shared",
    "pose_to_segments"
]